# Generated by Django 5.0.6 on 2024-05-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp_code',
            new_name='otp',
        ),
    ]
